### ISSUE TITLE
Error when fetching channel guide

### ISSUE THREAD

**Issue by LegendaryFire** [LegendaryFire/magplex#1]
```
2024-11-14 22:01:02,854 [ERROR]: Exception on /channel_guide.xml [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//main.py", line 61, in channel_guide
    guide = get_channel_guide()
            ^^^^^^^^^^^^^^^^^^^
  File "/cache.py", line 23, in wrapper
    result = cached_with_timestamp(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cache.py", line 12, in cached_with_timestamp
    result = func(*args)
             ^^^^^^^^^^^
  File "//main.py", line 76, in get_channel_guide
    guides = instance.get_channel_guide()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stb.py", line 182, in get_channel_guide
    results = self._get_list(url_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stb.py", line 135, in _get_list
    return run_batch()
           ^^^^^^^^^^^
  File "/stb.py", line 131, in run_batch
    batch_results = process_batch(batch_urls)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stb.py", line 124, in process_batch
    results = list(executor.map(fetch_url, batch_urls))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stb.py", line 116, in fetch_url
    response = self._get(url)
               ^^^^^^^^^^^^^^
  File "/stb.py", line 108, in _get
    data = json.loads(response.text).get('js', None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by LegendaryFire** [comment]
Implemented invalid value check in PR#2.
